apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Values.settings.env }}
  labels:
    app.kubernetes.io/name: {{ include "name" . }}-{{ .Values.settings.env }}
    app.kubernetes.io/part-of: {{ include "name" . }}-{{ .Values.settings.env }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-{{ .Values.settings.env }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  project_name: {{ .Values.settings.projectName | quote }}
  env: {{ .Values.settings.env | quote }}
  debug: {{ .Values.settings.debug | quote }}
  cors-allow-origin: {{ .Values.settings.corsAllowOrigin | quote }}
  trusted-proxies: {{ join "," .Values.settings.trustedProxies }}
  trusted-hosts: {{ .Values.settings.trustedHosts | quote }}
  project-name: {{ .Values.settings.projectName | quote }}
  php-service: {{ include "name" . }}-{{ .Values.settings.env }}-php
  
  varnish-url: {{ if .Values.varnish.enabled }}http://varnish{{ else }}{{ .Values.varnish.url | quote }}{{ end }}
  mercure-publish-url: {{ .Values.mercure.publishUrl | quote }}
  mercure-subscribe-url: {{ .Values.mercure.subscribeUrl | quote }}
