apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}-{{ .Values.settings.env }}
  labels:
    app.kubernetes.io/name: {{ include "name" . }}-{{ .Values.settings.env }}-ingress
    app.kubernetes.io/part-of: {{ include "name" . }}-{{ .Values.settings.env }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-{{ .Values.settings.env }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ .host | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /*
            backend:
              serviceName: {{ .serviceName }}
              servicePort: {{ .servicePort | default 80 }}
  {{- end }}
